---
version: "3.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_DIR}/docker/plex-config:/config
      - ${ROOT_DATA_DIR}/data/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/tautulli-config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/radarr-config:/config
      - ${ROOT_DATA_DIR}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/sonarr-config:/config
      - ${ROOT_DATA_DIR}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT_DIR}/docker/qbittorrent-config:/config
      - ${ROOT_DATA_DIR}/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"

  dcont:
    build:
      context: ${DCONT_PATH}
    restart: unless-stopped
    container_name: dcont
    depends_on: 
      - sonarr
      - qbittorrent
      - prowlarr
    volumes:
      - ./dcont-config.yml:/etc/dcont/config.yml
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      - RUST_LOG=INFO
